### ISSUE TITLE
will-mount and will-unmount mixins are not working as expected

### ISSUE THREAD

**Issue by ethagnawl** [Prismatic/om-tools#78]
I'm using ClojureScript 0-0-3211, Om 0.8.8 and Prismatic Tools 0.3.11. My apologies if I'm missing something obvious, this is my first attempt at using om-tools.mixin.

```
(enable-console-print!)
 
(defonce app-state (atom {:items [{:text "some text"}]}))
 
(defn items [] (om/ref-cursor (:items (om/root-cursor app-state))))
 
(defmixin mount-mixin
  (will-mount [_] (prn "i do not print 'will-mount'")))      ;; nothing is printed 
 
(defcomponent sub-view [data owner]
  (:mixins mount-mixin)
  (will-mount [_] (prn "i do print 'will-mount'"))
  (render [_]
    (let [xs (om/observe owner (items))]
      (when (> (count xs) 0)
        (dom/div nil
          (apply dom/ul nil
            (map #(dom/li nil (:text %)) xs)))))))
 
(om/root
  (fn [data owner]
    (reify om/IRender
      (render [_] (om/build sub-view data))))
  app-state
  {:target (. js/document (getElementById "app"))})
```

**Comment by JulianLeviston** [comment]
I'm curious - does the call to prn in the mixin will-mount work if you comment-out the component will-mount ?

**Comment by loganlinn** [comment]
@ethagnawl when you use mixins, you must pass a `:descriptor` option to `om/build` in order for the mixin to be added to the underlying React component. Om doesn't provide a way for a component to specify its own descriptor, so its up to whoever calls `om/build`.

om-tools automatically generates a descriptor when you use the `:mixins` option under the same name of your component + "$descriptor" suffix, ie `sub-view$descriptor`. It also generates a function that wraps `om/build` for your component to make this less painful.

```clojure
;; specify :descriptor option
(om/build sub-view data {:descriptor sub-view$descriptor})
;; or use generated build wrapper
(->sub-view data)
```

I understand this is not exactly ideal because the parent component must be aware of this special need.
That said, mixins are an experimental feature of om-tools (because of quirks like this) and the documentation certainly could be improved. Contributions welcome! :)

**Comment by ethagnawl** [comment]
@JulianLeviston No - the issue still stands.

@loganlinn Using the build wrapper works as expected. I'd totally glazed over the bit about factory functions in the mixins docs. Let me chew it over for a bit and see if I can add anything that'd make things more instructive for noobs like myself. Anyways, thanks for the response and the great library!
